apiVersion: v1
kind: ConfigMap
metadata:
  name: dora-config
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "name" . }}
data:
  greeting: {{ .Values.greeting | quote }}
